apiVersion: v1
kind: ConfigMap
metadata:
  name: reindex-job-config
  namespace: solrex
data:
  reindex.job.timeout: PT20M
  reindex.job.request: |
    source:
      cluster:
        baseUrl: http://solr-a:8983/solr
      collection: source_collection
    target:
      cluster:
        baseUrl: http://solr-b:8983/solr
      collection: target_collection
    fields:
      - id
      - title
      - category
