quarkus:
  application:
    name: reindex
  package:
    main-class: com.solrex.ReindexJobMain
  kubernetes-config:
    enabled: ${QUARKUS_KUBERNETES_CONFIG_ENABLED:false}
    fail-on-missing-config: ${QUARKUS_KUBERNETES_CONFIG_FAIL_ON_MISSING_CONFIG:false}
    namespace: ${REINDEX_K8S_NAMESPACE:solrex}
    config-maps: ${REINDEX_CONFIG_MAPS:reindex-job-config}

reindex:
  job:
    timeout: ${REINDEX_JOB_TIMEOUT:PT15M}
    request: |
      source:
        cluster:
          baseUrl: http://solr-a:8983/solr
        collection: source_collection
      target:
        cluster:
          baseUrl: http://solr-b:8983/solr
        collection: target_collection
      fields:
        - id
        - title
        - category
